#pragma once
#include <gl/glew.h>
#include <string>
#include <glm/gtc/matrix_transform.hpp>
#include "IchenLib/LoadMesh.h"
#include <unordered_map>
#include <regex>

class GraphicsBase
{
public:
	GraphicsBase();
	virtual ~GraphicsBase();

	bool Init_Shaders(const std::string vs, const std::string fs);
	bool Init_Shaders(const std::string vs, const std::string gs,const std::string fs);
	void Load_Model(const std::string model);

	// imgui auto generation
	void Generate_ImGui(const std::string shader_name);
	void Update_Uniforms();

	// Get && Set
	GLuint Get_Shader() const { return shader_program; }

	virtual void Draw() = 0;
	virtual void Draw_Shader_Uniforms() = 0;
	virtual void Reload() = 0;
	
	virtual void Init_Buffers() = 0;
	virtual void BufferManage() = 0;
	virtual void ReleaseBuffers() = 0;

protected:
	GLuint shader_program;
	std::string vs_file;
	std::string gs_file;
	std::string fs_file;
	MeshData mesh_data;

	// ImGui Autogenerated
	std::unordered_map<std::string, float> float_uniforms;
	std::unordered_map<std::string, bool> bool_uniforms;
	std::unordered_map<std::string, int> int_uniforms;
	std::unordered_map<std::string, glm::vec3> vec3_uniforms;
	std::unordered_map<std::string, glm::vec4> vec4_uniforms;

private:
	std::vector<std::string> allUniformNames;
	std::vector<GLenum> uniformTypes;

	void  Get_Uniforms_Names(const GLuint shader_program);
	bool isColor(std::string name)
	{
		std::regex rx("color");
		std::regex rx_upper("Color");
		return (std::regex_search(name, rx) || regex_search(name, rx_upper));
	}

};

